// src/lite/Routes.tsx
import { matchRoute } from "../router/matchRoute";
import { useRouter } from "../router/useRouter";
import { HomePage } from "./pages/HomePage";
import { AboutPage } from "./pages/AboutPage";
import { ExperiencePage } from "./pages/ExperiencePage";
import { ProjectsPage } from "./pages/ProjectsPage";
import { ProjectDetailPage } from "./pages/ProjectDetailPage";
import { BlogPage } from "./pages/BlogPage";
import { BlogPostPage } from "./pages/BlogPostPage";
import { MysteryPage } from "./pages/MysteryPage";
import { ContactPage } from "./pages/ContactPage";
import { SettingsPage } from "./pages/SettingsPage";
import { NotFoundPage } from "./pages/NotFoundPage";

export function Routes() {
  const { path } = useRouter();
  if (matchRoute("/", path)) return <HomePage />;
  if (matchRoute("/about", path)) return <AboutPage />;
  if (matchRoute("/experience", path)) return <ExperiencePage />;
  if (matchRoute("/projects", path)) return <ProjectsPage />;
  const projectMatch = matchRoute("/projects/:id", path);
  if (projectMatch) return <ProjectDetailPage projectId={projectMatch.params.id} />;
  if (matchRoute("/blog", path)) return <BlogPage />;
  const blogMatch = matchRoute("/blog/:id", path);
  if (blogMatch) return <BlogPostPage postId={blogMatch.params.id} />;
  if (matchRoute("/mystery", path)) return <MysteryPage />;
  if (matchRoute("/contact", path)) return <ContactPage />;
  if (matchRoute("/settings", path)) return <SettingsPage />;
  return <NotFoundPage />;
}

// src/lite/Routes.svelte
<script lang="ts">
  import { matchRoute } from "../router/matchRoute";
  import { getRouter } from "../router/routerContext";
  import HomePage from "./pages/HomePage.svelte";
  import AboutPage from "./pages/AboutPage.svelte";
  import ExperiencePage from "./pages/ExperiencePage.svelte";
  import ProjectsPage from "./pages/ProjectsPage.svelte";
  import ProjectDetailPage from "./pages/ProjectDetailPage.svelte";
  import BlogPage from "./pages/BlogPage.svelte";
  import BlogPostPage from "./pages/BlogPostPage.svelte";
  import MysteryPage from "./pages/MysteryPage.svelte";
  import ContactPage from "./pages/ContactPage.svelte";
  import SettingsPage from "./pages/SettingsPage.svelte";
  import NotFoundPage from "./pages/NotFoundPage.svelte";

  const router = getRouter();

  const projectMatch = $derived(matchRoute("/projects/:id", router.path));
  const blogMatch = $derived(matchRoute("/blog/:id", router.path));
</script>

{#if matchRoute("/", router.path)}
  <HomePage />
{:else if matchRoute("/about", router.path)}
  <AboutPage />
{:else if matchRoute("/experience", router.path)}
  <ExperiencePage />
{:else if matchRoute("/projects", router.path)}
  <ProjectsPage />
{:else if projectMatch}
  <ProjectDetailPage projectId={projectMatch.params.id} />
{:else if matchRoute("/blog", router.path)}
  <BlogPage />
{:else if blogMatch}
  <BlogPostPage postId={blogMatch.params.id} />
{:else if matchRoute("/mystery", router.path)}
  <MysteryPage />
{:else if matchRoute("/contact", router.path)}
  <ContactPage />
{:else if matchRoute("/settings", router.path)}
  <SettingsPage />
{:else}
  <NotFoundPage />
{/if}
