// src/shared/ExitToNormalButton.svelte
<script lang="ts">
  import "./exitToNormalButton.css";

  function handleClick(): void {
    const url = new URL(window.location.href);
    url.searchParams.set("mode", "fallback");
    window.location.assign(url.toString());
  }
</script>

<button type="button" class="exit-to-normal-button" onclick={handleClick}>
  Press for compatibility mode
</button>

// src/shared/ExitToNormalButton.tsx
import "./exitToNormalButton.css";

export function ExitToNormalButton() {
  function handleClick(): void {
    const url = new URL(window.location.href);
    url.searchParams.set("mode", "fallback");
    window.location.assign(url.toString());
  }

  return (
    <button type="button" className="exit-to-normal-button" onClick={handleClick}>
      Press for compatibility mode
    </button>
  );
}
