// src/lite/pages/BlogPage.tsx
import { Link } from "../../router/Link";
import { BLOG_POSTS } from "../../portfolio/content/blog";

export function BlogPage() {
  return (
    <article className="lite-page">
      <h1>Blog</h1>
      <p className="lite-lede">My ideas, thoughts, and stories.</p>
      <ul className="lite-card-list">
        {BLOG_POSTS.map((post) => (
          <li key={post.id}>
            <Link to={"/blog/" + post.id} className="lite-card">
              <div className="lite-card-meta">
                {post.icon ? post.icon + " " : ""}
                {post.tag} · {post.year} · {post.readtime}
              </div>
              <h2 className="lite-card-title">{post.title}</h2>
              <p className="lite-card-excerpt">{post.excerpt}</p>
            </Link>
          </li>
        ))}
      </ul>
    </article>
  );
}

// src/lite/pages/BlogPage.svelte
<script lang="ts">
  import Link from "../../router/Link.svelte";
  import { BLOG_POSTS } from "../../portfolio/content/blog";
</script>

<article class="lite-page">
  <h1>Blog</h1>
  <p class="lite-lede">My ideas, thoughts, and stories.</p>
  <ul class="lite-card-list">
    {#each BLOG_POSTS as post (post.id)}
      <li>
        <Link to={"/blog/" + post.id} class="lite-card">
          <div class="lite-card-meta">
            {post.icon ? post.icon + " " : ""}{post.tag} · {post.year} · {post.readtime}
          </div>
          <h2 class="lite-card-title">{post.title}</h2>
          <p class="lite-card-excerpt">{post.excerpt}</p>
        </Link>
      </li>
    {/each}
  </ul>
</article>
