// src/lite/pages/MysteryPage.tsx
import { PORTFOLIO } from "../../portfolio/data";

export function MysteryPage() {
  const items = PORTFOLIO.mystery;
  return (
    <article className="lite-page">
      <h1>Mystery</h1>
      <p className="lite-lede">Upcoming projects that aren't articulable yet.</p>
      {items.map((item) => (
        <div key={item.id} className="lite-mystery-card">
          <div className="lite-mystery-head">
            <span className="lite-mystery-codename">{item.codename}</span>
            <span className="lite-mystery-eta">ETA {item.eta}</span>
          </div>
          <div className="lite-mystery-expansion">{item.expansion}</div>
          <p>{item.hint}</p>
        </div>
      ))}
    </article>
  );
}

// src/lite/pages/MysteryPage.svelte
<script lang="ts">
  import { PORTFOLIO } from "../../portfolio/data";

  const items = PORTFOLIO.mystery;
</script>

<article class="lite-page">
  <h1>Mystery</h1>
  <p class="lite-lede">Upcoming projects that aren't articulable yet.</p>
  {#each items as item (item.id)}
    <div class="lite-mystery-card">
      <div class="lite-mystery-head">
        <span class="lite-mystery-codename">{item.codename}</span>
        <span class="lite-mystery-eta">ETA {item.eta}</span>
      </div>
      <div class="lite-mystery-expansion">{item.expansion}</div>
      <p>{item.hint}</p>
    </div>
  {/each}
</article>
