// src/lite/pages/ProjectsPage.svelte
<script lang="ts">
  import Link from "../../router/Link.svelte";
  import { PROJECTS } from "../../portfolio/content/projects";
</script>

<article class="lite-page">
  <h1>Projects</h1>
  <p class="lite-lede">Stuff I engineer on my own free will.</p>
  <p class="lite-lede">More coming soon.</p>
  <p class="lite-lede">I just didn't have time to do full writeups of everything yet.</p>
  <ul class="lite-card-list">
    {#each PROJECTS as project (project.id)}
      <li>
        <Link to={"/projects/" + project.id} class="lite-card">
          <div class="lite-card-meta">
            {project.tag} · {project.year}{project.status ? " · " + project.status : ""}
          </div>
          <h2 class="lite-card-title">{project.name}</h2>
          <p class="lite-card-excerpt">{project.oneliner}</p>
        </Link>
      </li>
    {/each}
  </ul>
</article>

// src/lite/pages/ProjectsPage.tsx
import { Link } from "../../router/Link";
import { PROJECTS } from "../../portfolio/content/projects";

export function ProjectsPage() {
  return (
    <article className="lite-page">
      <h1>Projects</h1>
      <p className="lite-lede">Stuff I engineer on my own free will.</p>
      <p className="lite-lede">More coming soon.</p>
      <p className="lite-lede">I just didn't have time to do full writeups of everything yet.</p>
      <ul className="lite-card-list">
        {PROJECTS.map((project) => (
          <li key={project.id}>
            <Link to={"/projects/" + project.id} className="lite-card">
              <div className="lite-card-meta">
                {project.tag} · {project.year}
                {project.status ? " · " + project.status : ""}
              </div>
              <h2 className="lite-card-title">{project.name}</h2>
              <p className="lite-card-excerpt">{project.oneliner}</p>
            </Link>
          </li>
        ))}
      </ul>
    </article>
  );
}
